### ISSUE TITLE
error when launching addin

### ISSUE THREAD

**Issue by FETmay** [paulgovan/QRAGadget#1]
hello,
I installed the package but when I launch I get an error 
> QRAGadget::QRAGadget()
The `name` provided ('picture-o') does not correspond to a known icon
Error in value[[3L]](cond) : 
  Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'tableinput'; `directoryPath` = ''

thnax in advance for your help

**Comment by paulgovan** [comment]
This was caused by a change in an upstream dependency. The dev version should work now. 

```
devtools::install_github('paulgovan/QRAGadget')
```
